receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  # Exportador simple 
  debug: {}

  # Exportador hacia Jaeger 
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp, debug]
